### PR TITLE
Annotations - disable save button on click

### LINKED ISSUE #3956: [Annotations] "Connection error" dialog is displayed for a moment if the "Save" button is clicked multiple times
[Notes]:
- Also, after clicking multiple times on the "Save" button the image is no longer displayed.

[Affected versions]:
- Nightly 59.0a1
- Screenshots 28.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 28.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and click the "Edit this image" button.
3. Draw something on the page.
4. Click multiple times on the "Save" button.
5. Observe the behavior.

[Expected result]:
- The changes are successfully saved without any errors. 

[Actual result]:
- "Connection error" dialog is displayed for a moment and the image is not displayed.

[Additional Notes]:
- Here is a screen recording with the issue:
connection error

### PR DESCRIPTION
**Pull request by niharikak101**
Fixes #3956

### CODE REVIEW

File: server/src/pages/shot/editor.js [hunk 1]
```diff
@@ -142,7 +142,7 @@ exports.Editor = class Editor extends React.Component {
       </div>
       <div className="shot-alt-actions annotation-alt-actions">
         <Localized id="annotationSaveButton">
-          <button className="button primary save" id="save" onClick={ this.onClickSave.bind(this) }>Save</button>
+          <button className="button primary save" id="save" onClick={ this.onClickSave.bind(this) } ref={(saveButton) => { this.saveButton = saveButton }}>Save</button>
```
Comment (chenba) [inline server/src/pages/shot/editor.js]: You can do this with using `ref`.  (See https://reactjs.org/docs/refs-and-the-dom.html for more `ref`.)

`disabled={this.state.ofWhatever}` and then set the appropriate state in `onClickSave()`.

**Comment by chenba** [comment]
I don't think we have styles for disabled primary buttons?  It'd be nice to have for this.
