### PR TITLE
fixed isOwner check on getAuthInfo

### LINKED ISSUE #2517: If you are already logged in and you navigate to someone else's shot, the change expire date, rename and delete the shot controls are available
[Notes]:
- If you use any of controls, you get a pop-up with a "404 Not Found" error. Probably because is not your shot.

[Affected versions]:
- Firefox 54.0a2 (Build ID:20170328004003)
- Page Shot 5.2.10545

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Firefox Screenshots (5.2.10545) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Perform a selection and save it.
3. In a new tab manually navigate to someone else's shot (https://pageshot.dev.mozaws.net/DkwWKUqnYZqq8asG/www.amazon.com).
4. Observe the shot preview page.

[Expected result]:
- The page is successfully loaded and the change expire date, rename and delete the shot controls are not displayed/available.

[Actual result]:
- The page is successfully loaded and the change expire date, rename and delete the shot controls are available.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/6mzuq0

### PR DESCRIPTION
**Pull request by dannycoates**
fixes #2517

### CODE REVIEW

File: addon/webextension/background/auth.js [hunk 1]
```diff
@@ -199,17 +199,12 @@ this.auth = (function () {
 
   communication.register("getAuthInfo", (sender, ownershipCheck) => {
     let info = registrationInfo;
-    let done = Promise.resolve();
     if (info.registered) {
-      done = login({ownershipCheck}).then((result) => {
-        if (result && result.isOwner) {
```
Comment (dannycoates) [inline addon/webextension/background/auth.js]: this line ended up being a one-way switch, once it was `isOwner` was true it could never be set back to false.
