### PR TITLE
hides 'copy image text' option if text capture is disabled

### LINKED ISSUE #2956: "Copy Image Text" option from context menu is available, even if the text capture is disabled
[Affected versions]:
- Nightly 55.0a1
- Sccreenshots 8.2.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the Nightly try build with Screenshots 8.2.0 installed and create a new profile.
- Screenshots Onboarding tour was already visited. 

[Steps to reproduce]:
1. Open the Nightly try build with Screenshots 8.2.0 installed with the profile from prerequisites.
2. Navigate to any website and save a selection.
3. Right click on the image and observe the context menu.

[Expected result]:
- The "Copy Image Text" option is no longer available.

[Actual results]:
- "Copy Image Text" option is still available.

### PR DESCRIPTION
**Pull request by niharikak101**
Fixes #2956

### CODE REVIEW

File: server/src/pages/shot/view.js [hunk 1]
```diff
@@ -80,6 +78,16 @@ class Clip extends React.Component {
     // Allow default action to continue
   }
 
+  textCaptureEnabled() {
```
Comment (ianb) [inline server/src/pages/shot/view.js]: `textCaptureEnabled` sounds like a true/false function. `textCaptureIfEnabled` would be a little clearer, but I would just name this `copyTextContextMenu()`.

Also it should return null at the end instead of the implicit return undefined.
