### PR TITLE
Fixes #5074 - Hide Signin banner on non-owned shot if authenticated

### LINKED ISSUE #5074: [FxA] The "Sign In" promo is wrongly displayed on a non-owner shot if it's opened on the Firefox profile where you are already logged
[Affected versions]:
- Nightly 65.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Screenshots FxA account with at least one saved shot.
- Have a profile where you are already logged in Screenshots FxA account.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Open a saved shot created on a different profile (eg: this [link](https://screenshots.dev.mozaws.net/KoETlKnQJ34ZC7Dk/www.wikipedia.org)).
3. Observe the shot page.

[Expected result]:
- The "Sign In" promo is not displayed.

[Actual results]:
- The "Sign In" promo is displayed even if you are already logged in.

[ Notes]:
- Here is a screen recording of the issue:
sign in promo on non owner

### PR DESCRIPTION
**Pull request by punamdahiya**
PR fixes hiding signin banner on non-owned shots if user has logged in on a device with Firefox Account.
Fix involves passing hasFxa prop to shotpag header that has accountId auth value set from cookie instead of isFxaAuthenticated value set in model.js that double checks if accountId cookie is same as associated accountId in database which will be false for non-owned shots

### CODE REVIEW

File: server/src/pages/shot/shotpage-header.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ exports.ShotPageHeader = class ShotPageHeader extends React.Component {
     if (this.props.isOwner) {
       return (
         <div className="shot-fxa-signin">
-          <SignInButton isFxaAuthenticated={this.props.isFxaAuthenticated} initialPage={this.props.shot.id}
+          <SignInButton isFxaAuthenticated={this.props.hasFxa} initialPage={this.props.shot.id}
```
Comment (6a68) [inline server/src/pages/shot/shotpage-header.js]: Is there any meaningful difference between `hasFxa` and `isFxaAuthenticated`? Do we need both?

**Comment by 6a68** [comment]
@punamdahiya feel free to self-merge if a review is approved with questions/comments :+1:

File: server/src/pages/shot/shotpage-header.js (hunk 1 above)
Comment (punamdahiya) [reply server/src/pages/shot/shotpage-header.js]: hasFxa determines its boolean value based off existence of accountId cookie, where as isFxaAuthenticated checks for both accountIdCookie and if the accountId cookie is linked to deviceId that has taken the shot ( const isFxaAuthenticated = req.accountId && req.accountId === req.shot.accountId;)

I have left isFxaAuthenticated in model as it's used by Favorite button enable/disable logic. I think now its safe to switch to hasFxa for favorite button logic as we are checking isOwner before displaying Favorite.

isOwner on shot page checks in database if shot is owned and linked to to a valid deviceId or accountId. I can update the PR with the change
