### PR TITLE
display fxa avatar

### LINKED ISSUE #3387: [FxA] If you are logged in, the default account picture is wrongly displayed instead of the chosen account picture
[Affected versions]:
- Nightly 56.0a1
- Screenshots 17.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pre is set to "false".
- Have a custom Screenshots dev build installed on a new Firefox profile.
- Have a FxA with an account picture.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a new tab.
2. Click the Screenshots icon from browser toolbar.
3. Click the "cogwheel" button from the right corner of the page.
4. Click the "Connect" button and sign in.
5. Observe the account picture.

[Expected result]:
- The chosen account picture is displayed.

[Actual results]:
- The default account picture is displayed instead of the chosen account picture.

[Notes]:
- Here is a screen recording with the issue:
profile picture

### PR DESCRIPTION
**Pull request by niharikak101**
Fixes #3387

### CODE REVIEW

File: server/src/config.js [hunk 1]
```diff
@@ -57,6 +57,13 @@ var conf = convict({
     arg: "s3BucketName"
   },
   fxa: {
+    server: {
+      doc: "The FxA server base URL",
+      format: String,
+      default: "https://stable.dev.lcip.org",
+      env: "FXA_SERVER",
```
Comment (ianb) [inline server/src/config.js]: This name is confusing – we're really thinking just about a base URL for profile images. And I notice that this matches the origin of the profileServer below.

File: server/src/server.js [hunk 2]
```diff
@@ -122,6 +122,7 @@ if (config.enableCoverage && istanbulMiddleware) {
 }
 
 const CONTENT_NAME = config.contentOrigin || '';
+const FXA_SERVER = config.fxa.server;
```
Comment (ianb) [inline server/src/server.js]: Now that I realize that this is the same as the profileServer, I think this should just be `config.fxa.profileServer && require("url").parse(config.fxa.profileServer).host`
