### PR TITLE
Send exceptions to raven when alert is called

### LINKED ISSUE #3303: Send exceptions to Raven whenever alert() is called
We have some places where we call alert() in the codebase, all generally unexpected fatal request errors. In each location we should also be sending information to Raven/Sentry.

### PR DESCRIPTION
**Pull request by niharikak101**
Fixes #3303

### CODE REVIEW

File: server/src/pages/settings/controller.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ exports.disconnectDevice = function() {
     if (req.status >= 300) {
       // FIXME: a lame way to do an error message
       window.alert("Error disconnecting: " + req.status + " " + req.statusText);
+      window.Raven.captureException(new Error("Error disconnecting"));
```
Comment (ianb) [inline server/src/pages/settings/controller.js]: This should have some more information. Probably it would be enough to have

    new Error(`Error disconnecting: ${req.status} ${req.statusText}`)

File: server/src/pages/shot/controller.js [hunk 2]
```diff
@@ -209,6 +214,7 @@ exports.setTitle = function(title) {
     if (req.status >= 300) {
       let errorMessage = document.getElementById("shotPageAlertErrorUpdatingTitle").textContent;
       window.alert(errorMessage);
+      window.Raven.captureException(new Error(`${errorMessage}: ${req.status} ${req.statusText}`));
```
Comment (ianb) [inline server/src/pages/shot/controller.js]: These should use something simpler than `${errorMessage}` – that's going to be localized, which will confuse things in Sentry.  Something like `Error calling /api/set-title: ${req.status} ${req.statusText}`
