### PR TITLE
Fixes #4622 - Stop using draggable attr.

### LINKED ISSUE #4622: [Annotations] The text caret cannot be placed inside written strings using the mouse
[Affected versions]:
- Nightly 63.0a1
- Dev Edition 62.0b7
- Release 61.0.1 Unbranded

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Screenshots v33.0.0dev installed.
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Click the "Add text" button and type some text.
4. Click in the middle of the text and observe the behavior.

[Expected result]:
- The text caret is displayed in the indicated position.

[Actual result]:
- The text caret remains at the end of the string.

[Notes]:
- This issue is not reproducible using the keyboard (arrow keys and "Home"/"End") keys.
- Here is a screen recording with this issue:
ss - text caret

### PR DESCRIPTION
**Pull request by chenba**
The draggable attr on the outer div was affecting the click behavior on the editable content div.  Stopping the click/mouse event bubbling didn't make a difference.

### CODE REVIEW

File: server/src/pages/shot/text-tool.js [hunk 1]
```diff
@@ -98,23 +101,46 @@ exports.TextTool = class TextTool extends React.Component {
     };
 
     return [
-      <div draggable="true" key="drag" onDragStart={this.onDragStart.bind(this)} style={dragDivStyles}>
+      <div key="drag" style={dragDivStyles}
+        onMouseDown={this.onDragMouseDown.bind(this)} onMouseUp={this.onMouseUp.bind(this)} onMove={this.onMouseMove.bind(this)}>
         <div id="text-input" ref={this.textInput} contentEditable="true" key="text" onKeyDown={this.onKeyDown.bind(this)}
-          onKeyUp={this.onKeyUp.bind(this)} className={`${this.state.textSize} ${this.state.colorName} text`} onFocus={this.moveCursorToEnd.bind(this)}>
```
Comment (punamdahiya) [inline server/src/pages/shot/text-tool.js]: Removing moveCursorToEnd brings back issue of type some text and then change the font color, the cursor is moved to the beginning of the input.

**Comment by chenba** [comment]
Click and drag to select entered text works now.
