### PR TITLE
Fix #5277, turn down logging if sendEvent fails

### LINKED ISSUE #5277: Ensure graceful failure for GA if server is gone
We want to be sure if the server is gone, that attempts to send information to GA fails gracefully.

### PR DESCRIPTION
**Pull request by ianb**
This also turns off sending events for the session if it ever gets a 410 Gone response

### CODE REVIEW

File: webextension/background/analytics.js [hunk 1]
```diff
@@ -307,15 +314,17 @@ this.analytics = (function() {
...
+    request.then(response => {
+      if (response.status === 410) { // Gone
+        hasReturnedGone = true;
+        pendingEvents = [];
+      }
+      if (!response.ok) {
+        log.debug(`Error code in event response: ${response.status} ${response.statusText}`);
+      }
+    }).catch(error => {
+      log.debug(`Error event in response: ${error}`);
```
Comment (6a68) [inline webextension/background/analytics.js]: Some users may not upgrade from 66 to 67 before the server is shut down in May, and `fetch` will throw if the server can't be found, so I think it'd be good to set `hasReturnedGone` inside this `catch`.

Comment (ianb) [reply webextension/background/analytics.js]: My hope is that we can put in a placeholder site before the site goes down completely. Unfortunately we can't tell the difference between the site being offline, and the computer being offline. I've made a followup in  #5293 to discuss this.
