### PR TITLE
Fix #hello onboarding

### LINKED ISSUE #4886: Make sure #hello triggers the onboarding tour

### PR DESCRIPTION
**Pull request by chenba**
Fixes #4886

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -362,6 +362,13 @@ describe("Test Screenshots", function() {
     }).catch(done);
   });
 
+  it("should show onboarding with #hello", async function() {
+    await driver.get(`${backend}/#hello`);
+    await driver.setContext(firefox.Context.CONTENT);
+    const slideFrame = await driver.wait(until.elementLocated(By.id(SLIDE_IFRAME_ID)));
+    assert(slideFrame, "Navgating to #hello should show onboarding");
```
Comment (6a68) [inline test/test.js]: "Navigating"
