### PR TITLE
When initing l10n, cache contents of FTL files, not user locale (#3170)

### LINKED ISSUE #3170: [l10n] seeing the wrong language on dev
My Firefox languages are en-US and en, but I"m seeing this on dev:

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #3170 for me locally

### CODE REVIEW

File: server/src/server.js [hunk 1]
```diff
@@ -291,21 +291,18 @@ app.use(function(req, res, next) {
...
-  l10n.init(languages).then(() => {
-    req.getText = l10n.getText;
-    req.userLocales = l10n.userLangs;
-    return l10n.getStrings().then(strings => {
-      req.messages = strings;
-      next();
-    });
-  }).catch(err => {
-    mozlog.info("l10n-error", {msg: "Error loading FTL files", description: err});
+  l10n.init().then(() => {
```
Comment (ianb) [inline server/src/server.js]: This (`l10n.init()`) is weird in a handler, but without #2208 I guess it's the best we got.

File: server/src/l10n.js [hunk 2]
```diff
@@ -6,98 +6,84 @@ const negotiateLanguages = require("fluent-langneg/compat");
...
 
-exports.init = function(userLocales = []) {
+const rawStrings = {};
+
+exports.init = function() {
   if (inited) {
     return Promise.resolve();
   }
   inited = true;
-  exports.userLangs = userLocales;
```
Comment (ianb) [inline server/src/l10n.js]: there's a possibility of a dogpile here, if multiple requests come in early. It should sort itself out, but I think it would be safer to do:

```
let initPromise;
exports.init = function() {
  if (initPromise) {
    return initPromise;
  }
  initPromise = globby(...);
  return initPromise;
};
```
