### PR TITLE
Fix 3005: Hides download firefox button

### LINKED ISSUE #3005: [Enhancement] The "Download Firefox" button should not be displayed on Onboarding page, if it's opened in Firefox
[Affected versions]:
- Nightly 55.0a1
- Sccreenshots 9.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Nightly build with Screenshots 9.0.0 installed and create a new profile.

[Steps to reproduce]:
1. Open the latest Nightly build with the profile from prerequisites.
2. Click the Screenshots button from browser toolbar.
3. Skip the "Onboarding" tour and observe the page.

[Expected result]:
- The "Download Firefox" button is not displayed.

[Actual results]:
- The "Download Firefox" button is displayed even if the Onboarding page it's opened in Firefox.

### PR DESCRIPTION
**Pull request by niharikak101**
fixes #3005

### CODE REVIEW

File: server/src/pages/homepage/model.js [hunk 1]
```diff
@@ -1,7 +1,8 @@
 exports.createModel = function(req) {
   let model = {
     title: "Firefox Screenshots",
-    showMyShots: !!req.deviceId
+    showMyShots: !!req.deviceId,
+    userAgent: req.headers['user-agent']
```
Comment (ianb) [inline server/src/pages/homepage/model.js]: I think it would be better here to do:

```js
let isFirefox = (/firefox\/\d{1,255}/i).test(req.headers['user-agent'])
```

and then put that in as a property of the model. Then the test is simpler in the view.

File: server/src/pages/homepage/view.js [hunk 2]
```diff
@@ -558,6 +558,23 @@ class Body extends React.Component {
     window.location = "/shots";
   }
 
+  renderGetFirefox() {
+    if (this.props.userAgent.search(/firefox\/\d{1,255}/i) === -1) {
```
Comment (ianb) [inline server/src/pages/homepage/view.js]: The logic would change based on the above comment, but generally I try to put exceptions first, so like:

```js
renderGetFirefox() {
  if (!this.props.isFirefox) {
    return null;
  }
  return ...
}
```
