### PR TITLE
Fix selection frame's position when content document's body's (left, top) is not at (0, 0).

### LINKED ISSUE #3907: Selection Rectangle Shifted to the Left Upon Clicking on Element
#### STR

1. Ensure your browser window is wide
1. Go to npr.org
1. Start Screenshots
1. Click on one of the stories to select it

#### Expected

Element correctly selected and highlighted

#### Actual 

image

### PR DESCRIPTION
**Pull request by chenba**
Fix #3907

### CODE REVIEW

File: addon/webextension/selector/ui.js [hunk 1]
```diff
@@ -8,28 +8,6 @@ this.ui = (function() { // eslint-disable-line no-unused-vars
...
-      right: rect.right + window.scrollX
-    };
-    // FIXME: I can't decide when this is necessary
-    // *not* necessary on http://patriciogonzalezvivo.com/2015/thebookofshaders/
-    // (actually causes mis-selection there)
-    // *is* necessary on http://atirip.com/2015/03/17/sorry-sad-state-of-matrix-transforms-in-browsers/
-    cached = {top: 0, bottom: 0, left: 0, right: 0};
-    getBodyRect.cached = cached;
-    return cached;
-  }
```
Comment (chenba) [inline addon/webextension/selector/ui.js]: Since this patch contains more cleanup than new code, it warrants a quick explanation.  `getBodyRect()` always returns a bunch of zeroes (ignoring its own calculations), two of which are used in additions and subtractions later.  I just did the add/subtract zero math myself.

File: addon/webextension/selector/ui.js [hunk 2]
```diff
@@ -619,25 +601,25 @@ this.ui = (function() { // eslint-disable-line no-unused-vars
       } else {
         this.el.classList.remove("left-selection");
       }
-      this.el.style.top = (pos.top - bodyRect.top) + "px";
-      this.el.style.left = (pos.left - bodyRect.left) + "px";
-      this.el.style.height = (pos.bottom - pos.top - bodyRect.top) + "px";
-      this.el.style.width = (pos.right - pos.left - bodyRect.left) + "px";
+      this.el.style.top = `${pos.top}px`;
+      this.el.style.left = `${pos.left}px`;
+      this.el.style.height = (pos.bottom - pos.top) + "px";
```
Comment (ianb) [inline addon/webextension/selector/ui.js]: For consistency I suppose these should be converted too. You can include any expression in a string substitution (i.e., `${pos.bottom - pos.top}px`)

Comment (chenba) [reply addon/webextension/selector/ui.js]: (huh not sure why I didn't receive any notification on that comment.)

I left those because I thought using parens for calculations is a little easier to read.  I'll change them to interpolated strings for consistency.
