### PR TITLE
Fix copy shot button race condition

### LINKED ISSUE #4957: The "Copy" button disappears/appears after the Shots page is refreshed
[Notes]:
- In certain cases the "Copy" button is not displayed on the Shots page after a shot is displayed. The button appears after the page is refreshed multiple times.
- If you edit the save shot, the "Copy" button disappears and is not displayed if you normally refresh the page. You need to refresh the page using the "Ctrl+F5/Cmd+F5" shortkey for the button to reappears.
- The "Copy" button does not disappear if the page is refresh using the "Ctrl+F5/Cmd+F5" shortkey.

[Affected versions]:
- Nightly 64.0a1
- Screenshots 34.0.0 dev

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 34.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to any website (eg:https://www.wikipedia.org/) and save a selection on the page.
3. Observe the "Copy" button.
4. Refresh the page and observe the "Copy" button.

[Expected result]:
Step 3 and Step 4: The "Copy" button is correctly displayed,

[Actual results]:
Step 3: The "Copy" button is correctly displayed.
Step 4. The "copy" button is no longer displayed. 

[Additional Notes]:
- Here is a screen recording of the issue:
copy button not displayedd

### PR DESCRIPTION
**Pull request by chenba**
Fixes #4957

### CODE REVIEW

File: server/src/pages/shot/controller.js [hunk 1]
```diff
@@ -280,15 +282,28 @@ exports.setTitle = function(title) {
...
+      // rendered content, it's performed after the initial rendering.
+      const delayedRender = () => {
+        if (initialRender) {
+          model.canCopy = true;
+          render();
+          return;
+        }
+        setTimeout(delayedRender, 50);
+      };
+      delayedRender();
```
Comment (6a68) [inline server/src/pages/shot/controller.js]: Hmm. It seems funny to use a setTimeout here, but I'm not sure of the best workaround.

What if we set `suppressHydrationWarning`, to signal that React should ignore the gap between server + client, or maybe set `state.isClient = true` inside `componentDidMount`, and checked the `canCopy` value from the model if `isClient`?

Comment (chenba) [reply server/src/pages/shot/controller.js]: `isClient` works great.  Thanks!  Also moved the event dispatch to a more sensible place.
