### PR TITLE
Fixes #4889 - Fix delete Shot button styles on my shots

### LINKED ISSUE #4889: [FxA] Delete Button on a Shot's Card on My Shots is Missing Its Styles
Not exactly FxA but it's caused by the patch from #4685 

image

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

**Comment by punamdahiya** [comment]
@chenba PR should fix broken delete button styles on myshots and ready for review. Thanks!

File: server/src/delete-shot-button.js [hunk 1]
```diff
@@ -75,16 +75,20 @@ exports.DeleteShotButton = class DeleteShotButton extends React.Component {
       deletePanelOpenClass = "active";
     }
 
+    const deleteButtonStyle = this.props.isIcon ? `button transparent trash ${deletePanelOpenClass}` :
+      `nav-button transparent icon-trash trash ${deletePanelOpenClass}`;
+    const deleteText = !this.props.isIcon ? <Localized id="shotPageDelete">
+        <span>Delete</span>
+      </Localized> : null;
```
Comment (chenba) [inline server/src/delete-shot-button.js]: nit: Both of these ternaries use `isIcon` as their condition, so consider use an if-else instead.

Comment (punamdahiya) [reply server/src/delete-shot-button.js]: Done. Thanks!
