### PR TITLE
Annotation Fixes

### LINKED ISSUE #3935: [Annotations] The black highlighter is not transparent and the white one is not visible
[Affected versions]:
- Nightly 59.0a1
- Screenshots 27.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 27.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and click the "Edit this image" button.
3. Select the "Highlighter" tool and choose the black color.
4. Draw something on the page and observe the highlighter.

[Expected result]:
- The highlighter is transparent.

[Actual result]:
- The highlighter is 100% opaque.

[Notes]:
- A similar behavior can be observed using the white highlighter, but in this case the color is not visible at all.
- Here is a screen recording with the issue:
black and white highlighter

### LINKED ISSUE #3987: [Annotations] Color Picker Should Close on Tool Selection
#### STR

1. Start editing a shot
1. Click the color picker tool icon to open the picker
1. Click on the highlighter to select it

#### Actual

The color picker remained open.

#### Expected

The color picker closes when I select a tool.

### LINKED ISSUE #4044: [Annotations] "Save" button can wrongly be actionated before the image is loaded
[Notes]:
- This issue is easier to encounter for large screenshots.

[Affected versions]:
- Nightly 60.0a1
- Screenshots v28.0.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- Have the latest Firefox Screenshots v28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) on a new clean profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to any website.
2. Click the "Page actions" button and select "Take a Screenshot".
3. Perform a large selection and click the "Save" button.
4. Click the "Edit this image" button.
5. Before the image is fully loaded, click the "Save" button.
6. Observe the behavior.

[Expected result]:
- The "Save" button is unactionable until the screenshot is fully loaded.

[Actual result]:
- The "Save" button is actionable and blank image is saved.

[Additional notes]:
- Here is a screen recording with the issue:
save button - screenshots

### PR DESCRIPTION
**Pull request by niharikak101**
Fix #4044 
Fix #3935 
Fix #3987

### CODE REVIEW

File: server/src/pages/shot/editor.js [hunk 1]
```diff
@@ -100,18 +100,20 @@ exports.Editor = class Editor extends React.Component {
...
       tool: 'pen',
       color: '#000',
-      size: '5'
+      size: '5',
+      saveDisabled: true
     };
   }
 
   render() {
+    let color = this.state.color == "rgb(255, 255, 255)" || this.state.color == "#FFF" ? "white" : null;
```
Comment (ianb) [inline server/src/pages/shot/editor.js]: This code is present several places, and isn't really complete (e.g., `#fff`). It might be fine that it isn't complete, but it should be in its own function (i.e., `isColorWhite(color)`) in case in the future it does need to be more complete

**Comment by niharikak101** [comment]
I also added a fix for #3934 and did a metrics review for annotations (#3997)
