### PR TITLE
Calculate pixel ratio from the image's natural size. (#4453, #4509)

### LINKED ISSUE #4453: [Annotations] Annotation tools are broken on smaller screens or if the page zoom level was changed before editing
[Notes]:
- On smaller screen (eg Mac Book Pro 13 inch) the issue is reproducible without changing the zoom level.

[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 32.1.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Change the the zoom level of the page (eg: 120%).
3. Click the "Edit this image" button.
4. Using the "Pen" tool draw a line on the page and observe the behavior.
5. Using the "Highlighter" tool draw a line on the page and observe the behavior.
6. Click the "Clear" button and observe the behavior.

[Expected result]:
Step 4: The line is correctly drawn on the image according to the mouse position.
Step 5: The line is correctly drawn on the image according to the mouse position.
Step 6: The changes are reverted.

[Actual results]:
Step 4: The line is drawn in a different position.
Step 5: The part of the image where drawing was performed is duplicated and displayed in a different position.
Step 6: The changes are reverted but the image is wrongly zoomed in.

[Additional Notes]:
- On smaller screens (eg: Mac Book Pro) the size of the drawing is also displayed smaller. 
- Here is a screen recording with the issue:
annotation tools

### PR DESCRIPTION
**Pull request by chenba**
- Ensure drawing canvas always match base canvas' dimensions.
- Scale a component's drawing context only when the canvas has been replaced.

Fix #4453, #4509

### CODE REVIEW

**Comment by chenba** [comment]
This patch is larger than expected because `window.devicePixelRatio` is affected by both system DPI scaling and page zoom level.  Since the shot's dimensions are CSS pixels at the time of capture, we cannot simply use `devicePixelRatio` to calculate the size of the canvas.  (E.g. A 100 x 100 shot from a "Retina" MBP would then have an editor canvas of 220 x 220 at 110% zoom.)

The shot image's natural size is now used to calculate a pixel ratio.  However, this ruffles the order of operations.  The main canvas cannot be rendered until the pixel ratio has been calculated, but that in turn has to wait for the image to load.  Much of the change in `editor.js` is to deal with that stuff.

File: server/src/pages/shot/editor.js [hunk 1]
```diff
@@ -30,12 +25,58 @@ exports.Editor = class Editor extends React.Component {
...
+      tool: "pen",
+      color: "#000",
+      lineWidth: 5,
+      actionsDisabled: true
+    });
+  }
+
+  componentDidUpdate(oldProps, oldState) {
+    if ((!oldState.canvasPixelRatio && this.state.canvasPixelRatio) ||
+        oldState.resetCanvas !== this.state.resetCanvas) {
```
Comment (chenba) [inline server/src/pages/shot/editor.js]: These are the two places when the original shot image is rendered: the initial rendering once the pixel ratio is available, and when the reset button's pressed.

**Comment by 6a68** [comment]
## 1. open an image in the editor

screen shot 2018-06-07 at 11 04 25 am

## 2. draw on it

screen shot 2018-06-07 at 11 04 38 am

## 3. revert.

screen shot 2018-06-07 at 11 04 42 am

**Comment by chenba** [comment]
😢 Thanks for the images!
