### PR TITLE
Synchronize startup code more carefully

### LINKED ISSUE #3257: Empty and unusable icon where Screenshots is supposed to be in Fx55 RC1
From IRC discussion in #fx-team, I'm still seeing bug 1381963 with Fx55 RC1 currently on the Beta channel. I've confirmed that version 10.9.0 of the Screenshots addon is installed.

Screenshot:
screenshots

Browser console logs:
DataError: Data provided to an operation does not meet requirements. (unknown)
	wrapMethods/cls.prototype[method] resource://gre/modules/IndexedDB.jsm:103:47
	get resource://gre/modules/ExtensionParent.jsm:1319:22
	next self-hosted:1179:9
CustomizableUI:unable to normalize widget  CustomizableUI.jsm:2179
aId is undefined  CustomizableUI.jsm:1267
	isSpecialWidget resource:///modules/CustomizableUI.jsm:1267:5
	getWidgetProvider resource:///modules/CustomizableUI.jsm:888:9
	wrapWidget resource:///modules/CustomizableUI.jsm:500:20
	createWidget resource:///modules/CustomizableUI.jsm:3308:12
	build chrome://browser/content/ext-browserAction.js:118:18
	onManifestEntry chrome://browser/content/ext-browserAction.js:104:5
	asyncEmitManifestEntry resource://gre/modules/ExtensionCommon.jsm:920:14
	next self-hosted:1179:9
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURIWithOptions]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: chrome://global/content/bindings/browser.xml :: loadURIWithFlags/< :: line 150"  data: no]  (unknown)
	loadURIWithFlags/< chrome://global/content/bindings/browser.xml:150:15
	_wrapURIChangeCall chrome://global/content/bindings/browser.xml:43:17
	loadURIWithFlags chrome://global/content/bindings/browser.xml:149:13
	loadURI/< chrome://global/content/bindings/browser.xml:114:15
	_wrapURIChangeCall chrome://global/content/bindings/browser.xml:43:17
	loadURI chrome://global/content/bindings/browser.xml:113:13
	build chrome://extensions/content/ext-backgroundPage.js:42:5
	next self-hosted:1179:9

### PR DESCRIPTION
**Pull request by 6a68**
I think everything's synchronized here, except shutdown is invoked without any way to pass back a callback or promise, so we might still see annoying issues with improper shutdown (that other bug)

hopefully fixes #3257

### CODE REVIEW

File: addon/bootstrap.js [hunk 1]
```diff
@@ -120,11 +122,13 @@ function start(webExtension) {
     if (err.message !== "This embedded extension has already been started") {
       // TODO: Should we send these errors to Sentry? #2420
     }
+    // TODO: necessary?
+    return Promise.resolve(null);
```
Comment (ianb) [inline addon/bootstrap.js]: This isn't necessary, the implied return undefined is enough here to swallow up the error.

**Comment by ianb** [comment]
This solves the problem for me (when I artificially create the problem in the code – the problem exists if I remove the `appStartupPromise` overwriting in this patch, but I can double-call `appStartupPromise = appStartupPromise.then(handleStartup)` without a problem)

File: addon/bootstrap.js (hunk 1 above)
Comment (6a68) [inline addon/bootstrap.js]: Thanks! Thought so, but feeling unsure about everything by this point
