### PR TITLE
Fixes #5146 - Copy string on myshots shows blank

### LINKED ISSUE #5146: The Copy string is not localized in supported languages and on certain cases the string is not displayed at all
[Affected versions]:
Nightly 65.0a1
Screenshots 34.0.0 dev

[Affected Platforms]:
Windows 10

[Prerequisites]:
- Have the latest Screenshots 34.0.0 dev version installed from here.
- Have several selections saved in the profile.
- Have the browser set to Spanish (Spain)

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to any website and click the "Take a Screenshot" from "Page Actions" menu.
3. Save a selection.
4. On the selection page, click on "All shots" button.
5. In "All shots" page, hover a shot, then click on "Share" button
6. See how "Copy" text is displayed on the button.

[Expected result]:
- The Copy string is localized in supported languages and  is displayed inside the button.

[Actual results]:
- The Copy string is not localized in supported languages and on certain cases the string is not displayed at all.

[Additional Notes]:
screenshots - chrome - copy button text
copy button spanish - english text

### PR DESCRIPTION
**Pull request by punamdahiya**

### CODE REVIEW

File: server/src/share-buttons.js [hunk 1]
```diff
@@ -155,10 +155,10 @@ class ShareButtonPanel extends React.Component {
           value={ this.props.shot.viewUrl }
           onClick={ this.onClickInputField.bind(this) }
           onChange={ function() {} /* react gives a warning otherwise */ } />
-        <Localized id={ this.state.copy === "copy" ? "shotPageCopy" : "shotPageCopied" }>
+        <Localized id={ this.state.copy === "copy" ? "shotPageCopyText" : "shotPageCopied" }>
```
Comment (flodolo) [inline server/src/share-buttons.js]: I'm confused. What was "shotPageCopy" before this PR?

File: locales/en-US/server.ftl [hunk 2]
```diff
@@ -100,6 +100,7 @@ shotPageShareButton =
     .title = Share
 shotPageCopyButton =
     .title = Copy image to clipboard
+shotPageCopyText = Copy
```
Comment (flodolo) [inline locales/en-US/server.ftl]: English is unclear (noun or verb?), I'd prefer a different ID to avoid confusion, e.g. shotPageCopyActionLabel (since `shotPageCopyButton` is already in use)

File: server/src/share-buttons.js (hunk 1 above)
Comment (punamdahiya) [reply server/src/share-buttons.js]: @flodolo that was for exact same text "Copy" but got removed in a PR that landed for new copy button on shots. 
Bringing it back with new id as we still need it on my shots page or can we still use the same id in this case?

File: locales/en-US/server.ftl (hunk 2 above)
Comment (punamdahiya) [reply locales/en-US/server.ftl]: It's a verb, will update with suggested ID

Comment (punamdahiya) [reply locales/en-US/server.ftl]: Done
