### PR TITLE
Oversample canvas on HiDPI screens

### LINKED ISSUE #3669: [Annotations] The saved shots looks blurry on "Edit" page
[Notes]:
- This issue is not reproducible on screens with retina and 4k displays.

[Affected versions]:
- Nightly 58.0a1
- Screenshots 22.0.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots dev version installed on a new clean profile.
- The Screenshots Onboarding tour was already visited.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any website.
2. Click the "Page Action" button.
3. Click the "Take a Screenshot" button and save a selection on the page.
4. Observe the saved shot.
5. Click the "Edit This Image" button and observe the shot.
6. Compare the two shot from Step 4 and Step 5.

[Expected result]:
- The shot looks visibly the same on both pages.

[Actual results]:
- The shot from Step 5 looks blurry.

[Additional Notes]:
- Here is a screen shot with the issue:
edtid page

### PR DESCRIPTION
**Pull request by niharikak101**
Fix #3669 
I haven't tested this on standard DPI screens, but the image quality should remain unchanged. The oversampling will only happen on HiDPI screens.

### CODE REVIEW

File: server/src/pages/shot/editor.js [hunk 1]
```diff
@@ -98,6 +99,7 @@ class Selection {
 exports.Editor = class Editor extends React.Component {
   constructor(props) {
     super(props);
+    this.devicePixelRatio = window.devicePixelRatio || 1;
```
Comment (chenba) [inline server/src/pages/shot/editor.js]: Nit: this default fallback is unnecessary.
