### PR TITLE
Fix #4652, bring textbox into view when refocusing

### LINKED ISSUE #4652: [Annotations] Text box is not brought into view when it is refocused
**[Affected versions]:**
- Nightly 63.0a1
- Dev Edition 62.0b8
- Release Unbranded

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
 - The "xpinstall.signatures.required" boolean pref is set to "false".
 - The "extensions.legacy.enabled" boolean pref is set to "true".
 - The "extensions.install.requireBuiltInCerts " boolean pref is set to "false"
 - Have the Screenshots 33.1.0 dev version installed from here, on a new clean profile.
 - Have a very long (over 2000px) shot saved.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites and navigate to my shots page. 
2. Click on the long shot and click on "Edit this image" button.
3. Click the "Add text" button.
4. Scroll down until the text box is no longer visible.
5. Change the text size and observe the behavior.

**[Expected result]:**
 - The text box is correctly focused and is in view.

**[Actual results]:**
 - The area below the text box is in view, but the text box is not in view.
 
 **[Notes]:**
 - This issue is also reproducible if you change the text color or type something when the text box is focused but is out of view.
 - This issue is not reproducible if the text box is below the visible area.
 - Screen recording with the issue: [link](https://drive.google.com/open?id=1QM0kBNWjZSDRoaTUQEiwo8dbF_OMtueL)

### PR DESCRIPTION
**Pull request by testeaxeax**
Fix #4652

### CODE REVIEW

File: server/src/pages/shot/text-tool.js [hunk 1]
```diff
@@ -152,7 +152,6 @@ exports.TextTool = class TextTool extends React.Component {
     this.setState({color, colorName});
 
     const txtInput = this.textInput.current;
-    txtInput.focus();
```
Comment (chenba) [inline server/src/pages/shot/text-tool.js]: We still want this.  Could you move it below the `scrollIntoView` if block?  Same with the change below.

**Comment by testeaxeax** [comment]
Sorry

**Comment by chenba** [comment]
@testeaxeax Thanks for the patch!
